version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: Banco_Digital
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: banco_digital
      MYSQL_USER: master
      MYSQL_PASSWORD: master123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]

volumes:
  mysql_data:
